#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "globinours"
name = "Globinours"
description.en = "Lightweight animal shelter management"
description.fr = "Gestion légère et complète pour refuges animaliers"
version = "1.0.0-rc.3~ynh3"
maintainers = ["OverSu"]

[upstream]
license = "AGPL-3.0-or-later"
code = "https://nnsprod.com/git/oversu/Globinours"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "300M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://nnsprod.com/git/oversu/Globinours/archive/63224d8b068f8dc0cc81be3536e0f56bd9a1bfa8.tar.gz"
    sha256 = "19b861ae8d944114360af3397182a338b9e536ac018b94577488a82413c9ee6d"
    in_subdir = true
    autoupdate.strategy = "latest_forgejo_commit"
    autoupdate.upstream = "https://nnsprod.com/git/oversu/Globinours"
    [resources.system_user]
    [resources.install_dir]
    [resources.data_dir]
    [resources.permissions]
    main.url = "/"
    [resources.apt]
    packages = "php8.2-fpm, php8.2-cli, php8.2-sqlite3, php8.2-mbstring, php8.2-xml, php8.2-zip, php8.2-gd, php8.2-curl, php8.2-intl, sqlite3"
