location __PATH__/ {
    alias __INSTALL_DIR__/public/;
    index index.php;
    client_max_body_size 260M;
    try_files $uri $uri/ @__APP__;
    location ~ /\. { deny all; }
}

location @__APP__ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME __INSTALL_DIR__/public/index.php;
    fastcgi_param HTTP_PROXY "";
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
}
